import pandas as pd

data_dict = [
    {
        'nama_kolom': 'user_id',
        'deskripsi': 'Kode pengenal unik/pseudonim untuk setiap individu responden dalam survei.',
        'tipe_data': 'string',
        'skala_pengukuran': 'Nominal',
        'satuan': '—',
        'contoh_nilai': 'USR-00001',
        'nilai_kosong': 'Tidak ada (0%)',
        'sumber': 'bedtime_screentime_sleep_debt.csv',
        'kategori_data_pribadi': 'Quasi-identifier',
        'tindakan_penanganan': 'Pertahankan / Hash',
        'catatan': 'Primary key (8.500 entri unik).'
    },
    {
        'nama_kolom': 'age',
        'deskripsi': 'Usia responden dalam satuan tahun saat survei dilaksanakan.',
        'tipe_data': 'int',
        'skala_pengukuran': 'Rasio',
        'satuan': 'Tahun',
        'contoh_nilai': '29',
        'nilai_kosong': 'Tidak ada (0%)',
        'sumber': 'bedtime_screentime_sleep_debt.csv',
        'kategori_data_pribadi': 'Quasi-identifier',
        'tindakan_penanganan': 'Generalisasi',
        'catatan': 'Disarankan dikelompokkan ke dalam rentang umur.'
    },
    {
        'nama_kolom': 'gender',
        'deskripsi': 'Identitas jenis kelamin yang dilaporkan secara mandiri oleh responden.',
        'tipe_data': 'string',
        'skala_pengukuran': 'Nominal',
        'satuan': '—',
        'contoh_nilai': 'Female',
        'nilai_kosong': 'Tidak ada (0%)',
        'sumber': 'bedtime_screentime_sleep_debt.csv',
        'kategori_data_pribadi': 'Quasi-identifier',
        'tindakan_penanganan': 'Pertahankan',
        'catatan': 'Terdiri dari 3 kategori: Female, Male, Non-Binary.'
    },
    {
        'nama_kolom': 'occupation_type',
        'deskripsi': 'Kategori bidang pekerjaan atau status profesi utama responden.',
        'tipe_data': 'string',
        'skala_pengukuran': 'Nominal',
        'satuan': '—',
        'contoh_nilai': 'Healthcare / Shift Worker',
        'nilai_kosong': 'Tidak ada (0%)',
        'sumber': 'bedtime_screentime_sleep_debt.csv',
        'kategori_data_pribadi': 'Quasi-identifier',
        'tindakan_penanganan': 'Pertahankan',
        'catatan': '5 kategori profesi utama.'
    },
    {
        'nama_kolom': 'chronotype',
        'deskripsi': 'Karakteristik pola biologis ritme sirkadian/tidur alami responden.',
        'tipe_data': 'string',
        'skala_pengukuran': 'Nominal',
        'satuan': '—',
        'contoh_nilai': 'Intermediate',
        'nilai_kosong': 'Tidak ada (0%)',
        'sumber': 'bedtime_screentime_sleep_debt.csv',
        'kategori_data_pribadi': 'Data spesifik',
        'tindakan_penanganan': 'Pertahankan',
        'catatan': 'Data fisiologis (Morning Lark, Intermediate, Night Owl).'
    },
    {
        'nama_kolom': 'bedtime_phone_minutes',
        'deskripsi': 'Durasi penggunaan ponsel sebelum tidur dalam satuan menit.',
        'tipe_data': 'int',
        'skala_pengukuran': 'Rasio',
        'satuan': 'Menit',
        'contoh_nilai': '179',
        'nilai_kosong': 'Tidak ada (0%)',
        'sumber': 'bedtime_screentime_sleep_debt.csv',
        'kategori_data_pribadi': 'Bukan data pribadi',
        'tindakan_penanganan': 'Pertahankan',
        'catatan': 'Nilai berkisar 1–180 menit.'
    },
    {
        'nama_kolom': 'primary_bedtime_app',
        'deskripsi': 'Aplikasi ponsel utama yang paling sering dibuka responden sebelum tidur.',
        'tipe_data': 'string',
        'skala_pengukuran': 'Nominal',
        'satuan': '—',
        'contoh_nilai': 'Instagram / Reddit',
        'nilai_kosong': 'Tidak ada (0%)',
        'sumber': 'bedtime_screentime_sleep_debt.csv',
        'kategori_data_pribadi': 'Bukan data pribadi',
        'tindakan_penanganan': 'Pertahankan',
        'catatan': '6 opsi kategori aplikasi.'
    },
]